#!/usr/bin/expect -f


set timeout 30

set server [lindex $argv 0]


spawn ssh $server
#spawn scp -r ../app ../shell $server:~

expect {
        "yes/no)?\ "  {send "yes\r";exp_continue}
       "*password:\ " {send "Mile1234\r"}
}

set cmdfile [lindex $argv 1]
expect "*]$\ " {
        while { [gets $cmdfile cmd] >= 0 } {
                send "$cmd\r"
        }
}

expect "*]#\ " {send "exit\r"}

expect eof
