#!/bin/bash
#please exe : sh hostname.sh hostname
IPADDR=`ifconfig |head -2 |tail -1 |awk '{split($2,a,":");print a[2]}'`
HOSTNM=$1
TYPE=$2
if [ $# -ne 2 ];then
    echo "exp: sh hostname.sh 主机名 类型()"
    exit
fi
if [ "x$TYPE" == "xg" ];then
cat > /etc/hosts <<EOF
127.0.0.1 localhost
$IPADDR $HOSTNM.b.m.net $HOSTNM.b.m $HOSTNM.b $HOSTNM
EOF
else
    echo "exp: sh hostname.sh 主机名 类型()"
    exit
fi
hostname $HOSTNM
cat > /etc/resolv.conf <<EOF
; generated by /sbin/dhclient-script
domain b.m.net
search b.m.net
nameserver 10.0.0.1
nameserver 1.1.9.1
EOF
cat > /etc/sysconfig/network <<EOF
NETWORKING=yes
HOSTNAME=$HOSTNM
EOF
